project_id = "xaxxdmvtfydqalswrneq"

[functions.kotak-neo-auth]
verify_jwt = false

[functions.kotak-place-order]
verify_jwt = false

[functions.kotak-market-data]
verify_jwt = false

[functions.kotak-ws-test]
verify_jwt = false
